In [17]:
import pandas as pd

In [18]:
raw = pd.read_excel("data/SP_2025.xlsx", sheet_name=0, header=None, dtype=str)
raw.head(12)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
0,Institutional Research & Planning\nSuccess & C...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,By Instructor ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,BY INSTRUCTOR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Division Name,NaN,Dept,Course,Name,Meth,Succ.,Compl,A,B,C,IPP,D,F,INP,W,Total
5,Behavioral & Social Sciences,NaN,AHIS,AHIS-101,"Ahmadpour, Alireza",HYBRD,0.43,0.96,8,3,-,1,-,12,3,1,28
6,NaN,NaN,NaN,NaN,NaN,ONLIN,0.23,0.99,13,4,2,1,-,58,8,1,87
7,NaN,NaN,NaN,NaN,"Alamillo, Lucy",HYBRD,0.55,0.71,8,6,3,-,-,5,-,9,31
8,NaN,NaN,NaN,NaN,"Beckstead\nWhitney, Karen",HYBRD,0.76,0.86,13,6,3,-,-,1,2,4,29
9,NaN,NaN,NaN,NaN,"Bronte, Andrea",ONLIN,0.13,1,1,2,-,-,-,20,-,-,23
10,NaN,NaN,NaN,NaN,"Majstorovic, Mina",ONLIN,0.71,0.97,20,3,4,-,2,8,-,1,38
11,NaN,NaN,NaN,NaN,"Potts, Gretchen",ONLIN,0.35,1,6,3,-,-,-,17,-,-,26

In [19]:
raw = raw.iloc[5:].reset_index(drop=True)
raw.head(12)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
0,Behavioral & Social Sciences,NaN,AHIS,AHIS-101,"Ahmadpour, Alireza",HYBRD,0.43,0.96,8,3,-,1,-,12,3,1,28
1,NaN,NaN,NaN,NaN,NaN,ONLIN,0.23,0.99,13,4,2,1,-,58,8,1,87
2,NaN,NaN,NaN,NaN,"Alamillo, Lucy",HYBRD,0.55,0.71,8,6,3,-,-,5,-,9,31
3,NaN,NaN,NaN,NaN,"Beckstead\nWhitney, Karen",HYBRD,0.76,0.86,13,6,3,-,-,1,2,4,29
4,NaN,NaN,NaN,NaN,"Bronte, Andrea",ONLIN,0.13,1,1,2,-,-,-,20,-,-,23
5,NaN,NaN,NaN,NaN,"Majstorovic, Mina",ONLIN,0.71,0.97,20,3,4,-,2,8,-,1,38
6,NaN,NaN,NaN,NaN,"Potts, Gretchen",ONLIN,0.35,1,6,3,-,-,-,17,-,-,26
7,NaN,NaN,NaN,NaN,"Robertson,\nCarolyn",ECC,0.8,1,21,17,5,-,3,8,-,-,54
8,NaN,NaN,NaN,NaN,"Russell, Elizabeth",ONLIN,0.78,0.85,28,2,2,-,-,3,-,6,41
9,NaN,NaN,NaN,AHIS-\n102A,"Alamillo, Lucy",ONLIN,0.75,0.94,24,16,13,-,4,10,-,4,71
10,NaN,NaN,NaN,AHIS-\n102AH,"Alamillo, Lucy",HYBRD,0.91,0.97,23,8,1,-,-,2,-,1,35
11,NaN,NaN,NaN,AHIS-\n102B,"Beckstead\nWhitney, Karen",HYBRD,0.79,0.91,35,6,3,-,2,5,-,5,56

In [20]:
if raw.shape[1] == 16:
    raw.columns = [
    "Division Name","Dept","Course","Name","Meth","Succ.","Compl",
    "A","B","C","IPP","D","F","INP","W","Total"
    ]
else: 
    raw.columns = [
    "Division Name","Dept_1", "Dept_2","Course","Name","Meth","Succ.","Compl",
    "A","B","C","IPP","D","F","INP","W","Total"
    ]
raw.head(8)

,Division Name,Dept_1,Dept_2,Course,Name,Meth,Succ.,Compl,A,B,C,IPP,D,F,INP,W,Total
0,Behavioral & Social Sciences,NaN,AHIS,AHIS-101,"Ahmadpour, Alireza",HYBRD,0.43,0.96,8,3,-,1,-,12,3,1,28
1,NaN,NaN,NaN,NaN,NaN,ONLIN,0.23,0.99,13,4,2,1,-,58,8,1,87
2,NaN,NaN,NaN,NaN,"Alamillo, Lucy",HYBRD,0.55,0.71,8,6,3,-,-,5,-,9,31
3,NaN,NaN,NaN,NaN,"Beckstead\nWhitney, Karen",HYBRD,0.76,0.86,13,6,3,-,-,1,2,4,29
4,NaN,NaN,NaN,NaN,"Bronte, Andrea",ONLIN,0.13,1,1,2,-,-,-,20,-,-,23
5,NaN,NaN,NaN,NaN,"Majstorovic, Mina",ONLIN,0.71,0.97,20,3,4,-,2,8,-,1,38
6,NaN,NaN,NaN,NaN,"Potts, Gretchen",ONLIN,0.35,1,6,3,-,-,-,17,-,-,26
7,NaN,NaN,NaN,NaN,"Robertson,\nCarolyn",ECC,0.8,1,21,17,5,-,3,8,-,-,54

In [22]:
raw["Total"] = pd.to_numeric(raw["Total"], errors="coerce")
raw['Total'].sum()

160512.0

In [23]:
raw["Dept"] = raw["Dept_1"].fillna(raw["Dept_2"])

In [24]:
raw = raw.drop(columns=["Dept_1", "Dept_2"])

In [25]:
raw.tail(50)

,Division Name,Course,Name,Meth,Succ.,Compl,A,B,C,IPP,D,F,INP,W,Total,Dept
1672,NaN,CHEM-7B,"Doucette, Peter",ECC,0.97,0.97,11,14,8,-,-,-,-,1,34.0,NaN
1673,NaN,GEOG-1,"Diminutto, Jose",ONLIN,0.62,0.89,21,12,6,-,2,15,-,7,63.0,GEOG
1674,NaN,NaN,"Gard, Julienne",ECC,0.88,0.94,25,17,27,-,1,3,-,5,78.0,NaN
1675,NaN,NaN,NaN,ONLIN,0.87,0.95,13,28,25,-,4,2,-,4,76.0,NaN
1676,NaN,GEOG-2,"Avrit, Sara",ECC,0.73,0.81,9,7,3,-,1,1,-,5,26.0,NaN
1677,NaN,GEOG-5,"Scott, Jason",ONLIN,0.66,0.98,22,11,6,-,1,18,-,1,59.0,NaN
1678,NaN,GEOG-6,"Avrit, Sara",ECC,0.95,0.95,14,4,-,-,-,-,-,1,19.0,NaN
1679,NaN,NaN,"Gard, Julienne",ONLIN,0.76,0.86,7,19,30,-,3,5,-,10,74.0,NaN
1680,NaN,GEOG-7,"Diaz, Kane",ONLIN,0.52,0.93,3,3,8,-,-,11,-,2,27.0,NaN
1681,NaN,GEOL-1,"Di Fiori, Sara",ONLIN,0.87,0.98,25,10,6,-,1,4,-,1,47.0,GEOL
1682,NaN,NaN,"Wageman, Jwan",ECC,1,1,12,12,10,-,-,-,-,-,34.0,NaN
1683,NaN,NaN,NaN,ONLIN,1,1,29,2,3,-,-,-,-,-,34.0,NaN
1684,NaN,GEOL-15,"Wageman, Jwan",ECC,0.69,0.88,12,4,6,-,-,6,-,4,32.0,NaN
1685,NaN,GEOL-3,"Di Fiori, Sara",ECC,0.89,0.89,3,4,10,-,-,-,-,2,19.0,NaN
1686,NaN,NaN,"Wageman, Jwan",ECC,1,1,22,7,5,-,-,-,-,-,34.0,NaN
1687,NaN,GEOL-6,"McCabe-Glynn,\nStaryl",ECC,0.89,0.92,26,7,-,-,-,1,-,3,37.0,NaN
1688,NaN,GEOL-7,"Noyes, Thomas",ONLIN,0.59,0.59,5,2,3,-,-,-,-,7,17.0,NaN
1689,NaN,MICR-33,"Bui, Thanh-Thuy",ECC,0.82,0.87,17,25,13,-,3,-,-,9,67.0,MICR
1690,NaN,NaN,"Hernandez,\nRebecca",HYBRD,0.84,0.92,17,12,3,-,2,1,-,3,38.0,NaN
1691,NaN,NaN,"Palos, Teresa",ECC,0.69,0.81,7,7,11,-,2,2,-,7,36.0,NaN
1692,NaN,NaN,"Parks, Polly",HYBRD,0.92,0.92,17,14,4,-,-,-,-,3,38.0,NaN
1693,NaN,OCEA-10,"Di Fiori, Sara",ECC,0.88,0.91,13,7,9,-,1,-,-,3,33.0,OCEA
1694,NaN,NaN,"Glynn, Danielle",ECC,0.97,0.98,42,16,5,-,-,1,-,1,65.0,NaN
1695,NaN,NaN,"Noyes, Thomas",HYBRD,0.45,0.85,-,4,5,-,3,5,-,3,20.0,NaN
1696,NaN,NaN,NaN,ONLIN,0.71,0.81,2,11,9,-,1,2,-,6,31.0,NaN
1697,NaN,NaN,"Sedki, Ziad",ONLIN,0.53,0.6,4,6,6,-,2,-,-,12,30.0,NaN
1698,NaN,NaN,"Wageman, Jwan",ECC,0.97,1,23,6,6,-,1,-,-,-,36.0,NaN
1699,NaN,PHYO-31,"Huynhle, Marvin",ECC,0.94,0.94,18,13,2,-,-,-,-,2,35.0,PHYO
1700,NaN,NaN,"Mubarak, Merium",ECC,0.82,0.86,25,14,20,-,1,2,-,10,72.0,NaN
1701,NaN,NaN,"Oswald, Sanda",ECC,0.91,0.91,23,6,-,-,-,-,-,3,32.0,NaN
1702,NaN,NaN,"Razee, Asif",ECC,0.96,1,10,14,1,-,-,1,-,-,26.0,NaN
1703,NaN,NaN,"Sanwo, Olusola",ECC,0.7,0.85,4,8,7,-,3,1,-,4,27.0,NaN
1704,NaN,PHYS-11,"Scott, Christopher",ONLIN,0.69,0.72,26,10,11,-,1,1,-,19,68.0,PHYS
1705,NaN,PHYS-1A,"Haitkin, Paul",ECC,0.69,0.73,24,14,3,-,2,-,-,16,59.0,NaN
1706,NaN,NaN,"Murdock, Adam",ECC,0.87,0.87,21,3,3,-,-,-,-,4,31.0,NaN
1707,NaN,NaN,"Stolovy, Susan",ECC,0.57,0.6,5,6,6,-,-,1,-,12,30.0,NaN
1708,NaN,PHYS-1B,"Coroneus, John",ECC,0.62,0.79,4,7,7,-,-,5,-,6,29.0,NaN
1709,NaN,NaN,"Semsar, Parvaneh",ECC,0.93,0.93,17,9,1,-,-,-,-,2,29.0,NaN
1710,NaN,PHYS-1C,"Coroneus, John",ECC,0.53,0.67,10,13,14,-,4,6,-,23,70.0,NaN
1711,NaN,NaN,"Shirvanian, Razmic",ECC,0.48,0.7,3,3,5,-,1,4,-,7,23.0,NaN
1712,NaN,PHYS-1D,"Goldmann, Eyal",ECC,0.77,0.9,12,8,4,-,-,3,1,3,31.0,NaN
1713,NaN,NaN,"Stolovy, Susan",ECC,0.87,0.87,14,6,6,-,-,-,-,4,30.0,NaN
1714,NaN,PHYS-2A,"Demir, Firuz",HYBRD,0.5,0.7,7,4,4,-,2,3,1,9,30.0,NaN
1715,NaN,NaN,"Goldmann, Eyal",ECC,0.59,0.62,3,8,9,-,-,1,-,13,34.0,NaN
1716,NaN,NaN,"Haitkin, Paul",ECC,0.69,0.87,23,15,9,-,1,11,-,9,68.0,NaN
1717,NaN,PHYS-2B,"Said, Asma",ECC,0.87,1,7,4,9,-,1,2,-,-,23.0,NaN
1718,NaN,PHYS-3A,"Demir, Firuz",ECC,0.8,0.87,5,4,3,-,-,1,-,2,15.0,NaN
1719,NaN,PHYS-3B,"Van Biezen,\nMichel",ECC,0.87,0.97,11,5,10,-,3,-,-,1,30.0,NaN
1720,Natural Sciences\nTotal,NaN,NaN,NaN,0.73,0.85,1667,1089,793,2,193,348,4,747,4843.0,NaN
1721,Grand Total,NaN,NaN,NaN,0.72,0.86,22120,9454,5333,1447,1443,5431,625,7655,53508.0,NaN

In [26]:
prof_rows = raw[raw["Name"] == "Murdock, Adam"]
prof_rows

,Division Name,Course,Name,Meth,Succ.,Compl,A,B,C,IPP,D,F,INP,W,Total,Dept
1706,NaN,NaN,"Murdock, Adam",ECC,0.87,0.87,21,3,3,-,-,-,-,4,31.0,NaN

In [27]:
raw = raw.ffill()

In [96]:
raw.head(28)

,Division Name,Dept_1,Course,Name,Meth,Succ.,Compl,A,B,C,IPP,D,F,INP,W,Total
0,Behavioral & Social Sciences,AHIS,AHIS-101,"Ahmadpour, Alireza",ONLIN,0.88,0.99,56,5,4,-,-,6,2,1,74
1,Behavioral & Social Sciences,AHIS,AHIS-\n102A,"Robertson,\nCarolyn",ECC,0.87,1,19,3,5,-,1,3,-,-,31
2,Behavioral & Social Sciences,AHIS,AHIS-\n102B,"Beckstead\nWhitney, Karen",ONLIN,0.88,0.95,22,11,2,-,-,3,-,2,40
3,Behavioral & Social Sciences,ANTH,ANTH-1,"Otero, Rodolfo",ONLIN,0.95,0.98,17,18,4,-,-,1,-,1,41
4,Behavioral & Social Sciences,ANTH,ANTH-1,"Ramirez,\nLawrence",ECC,0.96,0.96,14,6,3,-,-,-,-,1,24
5,Behavioral & Social Sciences,ANTH,ANTH-1,"Vigil, Alberto",ECC,0.95,0.95,14,4,2,-,-,-,-,1,21
6,Behavioral & Social Sciences,ANTH,ANTH-1,"Wong, Billy",ONLIN,1,1,25,5,2,-,-,-,-,-,32
7,Behavioral & Social Sciences,ANTH,ANTH-11,"Otero, Rodolfo",ONLIN,0.87,0.91,12,8,-,-,-,1,-,2,23
8,Behavioral & Social Sciences,ANTH,ANTH-1H,"Waters, Marianne",ONLIN,1,1,53,4,1,-,-,-,-,-,58
9,Behavioral & Social Sciences,ANTH,ANTH-2,"Mannen, Angela",ONLIN,0.92,0.96,15,5,4,-,-,1,-,1,26
10,Behavioral & Social Sciences,CDEV,CDEV-\n103,"Jefferis, Janice",ONLIN,0.84,0.95,22,10,4,-,-,5,-,2,43
11,Behavioral & Social Sciences,CDEV,CDEV-\n103,"Marquez, Valerie",ONLIN,0.64,0.86,12,2,4,-,-,6,-,4,28
12,Behavioral & Social Sciences,CDEV,CDEV-\n103,"Moutra, Reshon",ECC,0.79,0.86,19,2,1,-,-,2,-,4,28
13,Behavioral & Social Sciences,CDEV,CDEV-\n104,"Marano, Mark",ONLIN,0.71,0.89,17,7,3,-,2,5,-,4,38
14,Behavioral & Social Sciences,CDEV,CDEV-\n107,"Jefferis, Janice",ONLIN,0.89,0.94,17,11,3,-,-,2,-,2,35
15,Behavioral & Social Sciences,CDEV,CDEV-\n110,"Marquez, Valerie",ONLIN,0.86,0.97,18,7,-,-,1,2,-,1,29
16,Behavioral & Social Sciences,CDEV,CDEV-\n110,"Tharuvai, Shanthi",ONLIN,0.62,0.81,9,3,1,-,-,4,-,4,21
17,Behavioral & Social Sciences,COMS,COMS-\n100,"Anderson, Julia",ECC,0.92,0.93,37,12,5,-,1,-,-,4,59
18,Behavioral & Social Sciences,COMS,COMS-\n100,"Bishop, Francesca",ONLIN,0.81,0.92,35,10,5,-,-,7,-,5,62
19,Behavioral & Social Sciences,COMS,COMS-\n100,"Crossman, Diana",ONLIN,0.77,0.93,28,9,10,-,5,5,-,4,61
20,Behavioral & Social Sciences,COMS,COMS-\n100,"Crossman, Mark",ONLIN,0.93,0.95,44,4,5,-,1,-,-,3,57
21,Behavioral & Social Sciences,COMS,COMS-\n100,"Evans, Joseph",ONLIN,0.87,0.97,26,-,-,-,-,2,1,1,30
22,Behavioral & Social Sciences,COMS,COMS-\n100,"Hubble, Brittany",ONLIN,1,1,21,3,1,-,-,-,-,-,25
23,Behavioral & Social Sciences,COMS,COMS-\n100,"Lopez, Rodolfo",ECC,0.82,0.89,31,8,6,-,1,3,-,6,55
24,Behavioral & Social Sciences,COMS,COMS-\n100,"Matos, Julie",ONLIN,0.84,0.88,19,2,-,-,-,1,-,3,25
25,Behavioral & Social Sciences,COMS,COMS-\n100,"Matthews, Julia",ONLIN,0.68,0.76,5,7,5,-,-,2,-,6,25
26,Behavioral & Social Sciences,COMS,COMS-\n100,"Ortega, Valerie",ONLIN,0.85,0.95,14,2,1,-,-,1,1,1,20
27,Behavioral & Social Sciences,COMS,COMS-\n100,"Peterson, Elyse",ONLIN,0.69,0.92,3,9,6,-,1,5,-,2,26

In [28]:
raw['Total'].sum()

160686.0

In [97]:
raw = raw.replace("-", 0)

In [98]:
raw.head(28)

,Division Name,Dept_1,Course,Name,Meth,Succ.,Compl,A,B,C,IPP,D,F,INP,W,Total
0,Behavioral & Social Sciences,AHIS,AHIS-101,"Ahmadpour, Alireza",ONLIN,0.88,0.99,56,5,4,0,0,6,2,1,74
1,Behavioral & Social Sciences,AHIS,AHIS-\n102A,"Robertson,\nCarolyn",ECC,0.87,1,19,3,5,0,1,3,0,0,31
2,Behavioral & Social Sciences,AHIS,AHIS-\n102B,"Beckstead\nWhitney, Karen",ONLIN,0.88,0.95,22,11,2,0,0,3,0,2,40
3,Behavioral & Social Sciences,ANTH,ANTH-1,"Otero, Rodolfo",ONLIN,0.95,0.98,17,18,4,0,0,1,0,1,41
4,Behavioral & Social Sciences,ANTH,ANTH-1,"Ramirez,\nLawrence",ECC,0.96,0.96,14,6,3,0,0,0,0,1,24
5,Behavioral & Social Sciences,ANTH,ANTH-1,"Vigil, Alberto",ECC,0.95,0.95,14,4,2,0,0,0,0,1,21
6,Behavioral & Social Sciences,ANTH,ANTH-1,"Wong, Billy",ONLIN,1,1,25,5,2,0,0,0,0,0,32
7,Behavioral & Social Sciences,ANTH,ANTH-11,"Otero, Rodolfo",ONLIN,0.87,0.91,12,8,0,0,0,1,0,2,23
8,Behavioral & Social Sciences,ANTH,ANTH-1H,"Waters, Marianne",ONLIN,1,1,53,4,1,0,0,0,0,0,58
9,Behavioral & Social Sciences,ANTH,ANTH-2,"Mannen, Angela",ONLIN,0.92,0.96,15,5,4,0,0,1,0,1,26
10,Behavioral & Social Sciences,CDEV,CDEV-\n103,"Jefferis, Janice",ONLIN,0.84,0.95,22,10,4,0,0,5,0,2,43
11,Behavioral & Social Sciences,CDEV,CDEV-\n103,"Marquez, Valerie",ONLIN,0.64,0.86,12,2,4,0,0,6,0,4,28
12,Behavioral & Social Sciences,CDEV,CDEV-\n103,"Moutra, Reshon",ECC,0.79,0.86,19,2,1,0,0,2,0,4,28
13,Behavioral & Social Sciences,CDEV,CDEV-\n104,"Marano, Mark",ONLIN,0.71,0.89,17,7,3,0,2,5,0,4,38
14,Behavioral & Social Sciences,CDEV,CDEV-\n107,"Jefferis, Janice",ONLIN,0.89,0.94,17,11,3,0,0,2,0,2,35
15,Behavioral & Social Sciences,CDEV,CDEV-\n110,"Marquez, Valerie",ONLIN,0.86,0.97,18,7,0,0,1,2,0,1,29
16,Behavioral & Social Sciences,CDEV,CDEV-\n110,"Tharuvai, Shanthi",ONLIN,0.62,0.81,9,3,1,0,0,4,0,4,21
17,Behavioral & Social Sciences,COMS,COMS-\n100,"Anderson, Julia",ECC,0.92,0.93,37,12,5,0,1,0,0,4,59
18,Behavioral & Social Sciences,COMS,COMS-\n100,"Bishop, Francesca",ONLIN,0.81,0.92,35,10,5,0,0,7,0,5,62
19,Behavioral & Social Sciences,COMS,COMS-\n100,"Crossman, Diana",ONLIN,0.77,0.93,28,9,10,0,5,5,0,4,61
20,Behavioral & Social Sciences,COMS,COMS-\n100,"Crossman, Mark",ONLIN,0.93,0.95,44,4,5,0,1,0,0,3,57
21,Behavioral & Social Sciences,COMS,COMS-\n100,"Evans, Joseph",ONLIN,0.87,0.97,26,0,0,0,0,2,1,1,30
22,Behavioral & Social Sciences,COMS,COMS-\n100,"Hubble, Brittany",ONLIN,1,1,21,3,1,0,0,0,0,0,25
23,Behavioral & Social Sciences,COMS,COMS-\n100,"Lopez, Rodolfo",ECC,0.82,0.89,31,8,6,0,1,3,0,6,55
24,Behavioral & Social Sciences,COMS,COMS-\n100,"Matos, Julie",ONLIN,0.84,0.88,19,2,0,0,0,1,0,3,25
25,Behavioral & Social Sciences,COMS,COMS-\n100,"Matthews, Julia",ONLIN,0.68,0.76,5,7,5,0,0,2,0,6,25
26,Behavioral & Social Sciences,COMS,COMS-\n100,"Ortega, Valerie",ONLIN,0.85,0.95,14,2,1,0,0,1,1,1,20
27,Behavioral & Social Sciences,COMS,COMS-\n100,"Peterson, Elyse",ONLIN,0.69,0.92,3,9,6,0,1,5,0,2,26

In [99]:
prof_rows = raw[raw["Name"] == "Murdock, Adam"]
prof_rows

,Division Name,Dept_1,Course,Name,Meth,Succ.,Compl,A,B,C,IPP,D,F,INP,W,Total
331,Natural Sciences,PHYS,PHYS-1B,"Murdock, Adam",ECC,1,1,26,3,2,0,0,0,0,0,31

In [100]:
raw.shape[1]

16

In [73]:
cols = raw.columns.tolist()
cols.remove("Dept")
cols.insert(1, "Dept")
df = raw[cols]

In [79]:
df.tail()

,Division Name,Dept,Course,Name,Meth,Succ.,Compl,A,B,C,IPP,D,F,INP,W,Total
1717,Natural Sciences,PHYS,PHYS-2B,"Said, Asma",ECC,0.87,1,7,4,9,0,1,2,0,0,23
1718,Natural Sciences,PHYS,PHYS-3A,"Demir, Firuz",ECC,0.8,0.87,5,4,3,0,0,1,0,2,15
1719,Natural Sciences,PHYS,PHYS-3B,"Van Biezen,\nMichel",ECC,0.87,0.97,11,5,10,0,3,0,0,1,30
1720,Natural Sciences\nTotal,PHYS,PHYS-3B,"Van Biezen,\nMichel",ECC,0.73,0.85,1667,1089,793,2,193,348,4,747,4843
1721,Grand Total,PHYS,PHYS-3B,"Van Biezen,\nMichel",ECC,0.72,0.86,22120,9454,5333,1447,1443,5431,625,7655,53508

In [80]:
df.to_csv("output.csv", index=False)

In [120]:
df["Name"].dtype

dtype('O')

In [121]:
df["A"] = pd.to_numeric(df["A"])

In [122]:
df["A"].dtype

dtype('float64')

In [4]:
import pandas as pd
path1 = "/Users/serenazhu/Desktop/rmp/FA_2024.csv"
path2 = "/Users/serenazhu/Desktop/rmp/SU_2024.csv"

data1 = pd.read_csv(path1)
data2 = pd.read_csv(path2)

all_df = pd.concat([data1, data2], ignore_index=True)
sum_cols = ["A","B","C","D","F","Total"]
rate_cols = ["Compl","Succ."]

merged = (
    all_df.groupby("Name", as_index=False)
    .agg({
        "Dept": "first", 
        **{c: "sum" for c in sum_cols},
        **{c: "mean" for c in rate_cols},}
    )
)
merged.head()

                    Name  Dept   A   B   C   D   F  Total  Compl     Succ.
0         Abbani, Cheryl  ANAT   9   9   7   1   0     29   0.90  0.860000
1        Abbani, Mohamad  CHEM  13  10  16  10   5     79   0.68  0.490000
2  Abdelhamid,\nMohammed  PSYC  35  27  19  11  10    110   0.93  0.693333
3        Acosta, Joaquin  ENGL   4   5   9   3   5     58   0.90  0.670000
4      Acquarelli, James    AJ  58   4   3   1   3     81   0.89  0.820000

In [5]:
prof_rows = merged[merged["Name"] == "Murdock, Adam"]

In [6]:
prof_rows

              Name  Dept   A   B   C  D  F  Total  Compl     Succ.
527  Murdock, Adam  PHYS  46  33  26  3  9    133    0.9  0.806667

In [14]:
path2 = "/Users/serenazhu/Desktop/rmp/merged.csv"
df1 = pd.read_csv(path2)
merged = pd.read_csv(path2)

In [15]:
len(df1)

834

In [16]:
len(merged)

834

In [30]:
raw = pd.read_excel("data/excel/SP_2024.xlsx", sheet_name=0, header=None, dtype=str)

In [31]:
raw.tail()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
1829,NaN,NaN,PHYS-3B,"Van Biezen, Michel",ECC,0.82,0.94,10,9,9,-,1,3,-,2,34
1830,Natural Sciences\nTotal,NaN,NaN,NaN,NaN,0.73,0.84,NaN,1199,802,2,211,316,1,747,4661
1831,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1383,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1832,Grand Total,NaN,NaN,NaN,NaN,0.71,0.85,NaN,10096,5613,1396,1704,4865,575,7902,52384
1833,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"20,23\n3",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [34]:
2.4%1

0.3999999999999999